on:
  push:
    branches:
      
name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Create version
      uses: ./
      with:
        script: './build.sh'
      env:
        TOKEN: ${{ secrets.TOKEN }}
        
