on:
  push:
      
name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Create version
      uses: ./
      with:
        version: 'v1.0.7'
        
